'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FormulirInformasiNasabah

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tblc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblc As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lbljudul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljudul As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltrlFIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlFIN As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txaLatarBelakang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txaLatarBelakang As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltrlLegalitasUsaha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlLegalitasUsaha As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txaLegalitasUsaha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txaLegalitasUsaha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtpemegangsaham control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpemegangsaham As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltrlKepemilikanPerusahaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlKepemilikanPerusahaan As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litkeyperson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litkeyperson As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtsusunanpengurus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsusunanpengurus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltrlPengurusdanPenilaianManajemen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlPengurusdanPenilaianManajemen As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtpengursumanagemen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpengursumanagemen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltrlProfilManajemenPerusahaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlProfilManajemenPerusahaan As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txaPenilaianManajemen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txaPenilaianManajemen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''litSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSignature As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlExportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExportType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport As Global.System.Web.UI.WebControls.Button
End Class
