'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_FormulirInfoAgunan

    '''<summary>
    '''liBodyLoadAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liBodyLoadAction As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tblFia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFia As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lbljudul1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljudul1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''littgl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents littgl As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblheader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblheader1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litagunan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtmsg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg2 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblheader2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblheader2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblket1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmsg1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg1 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''littextarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents littextarea As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litagunan2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtmsg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg3 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblket2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmsg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg4 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''litagunan3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblket3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmsg5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg5 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''litagunan4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan4 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtmsg6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg6 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtmsg7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg7 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtmsg8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg8 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblheader3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblheader3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmsg9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg9 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''litagunan5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan5 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtmsg10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg10 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtmsg11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg11 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtmsg12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg12 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''litagunan6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan6 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtmsg13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg13 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblheader4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblheader4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblket4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litagunan7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan7 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtmsg14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg14 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblket5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litagunan8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litagunan8 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblket6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmsg15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg15 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtmsg16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg16 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblket7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmsg17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg17 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''lblket8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblket8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmsg18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmsg18 As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''litSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSignature As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExport2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport2 As Global.System.Web.UI.WebControls.Button
End Class
