'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IkhtisarPengusulanKredit

    '''<summary>
    '''liBodyLoadAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liBodyLoadAction As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lbljudul1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljudul1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litIPK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litIPK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litIPK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litIPK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK4 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litPerofilRisiko control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPerofilRisiko As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litIPK5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK5 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litIPK6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK6 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblAudtor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAudtor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtaudit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaudit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblappraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblappraisal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAppraisel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAppraisel As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblmargin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmargin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmarginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmarginal As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblother As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtother As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''litIPK7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK7 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtpejabat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpejabat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtkomite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtkomite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''litIPK8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litIPK8 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblKMK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKMK1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litKetentuanKMK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKetentuanKMK1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKetentuanKMKAgunan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKetentuanKMKAgunan As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKetentuanKMKFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKetentuanKMKFixed As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litKetentuanKMKFixedTunai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litKetentuanKMKFixedTunai As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblSPPK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPPK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPerjanjianKredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPerjanjianKredit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblkmk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblkmk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEfektifKMK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEfektifKMK1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblpenariknKMK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpenariknKMK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPenarikanKMK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPenarikanKMK2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblsyaratSwitchable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsyaratSwitchable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFasilitasKMK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFasilitasKMK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSyarat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSyarat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSyaratLainnya control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSyaratLainnya As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''litSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSignature As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExport2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport2 As Global.System.Web.UI.WebControls.Button
End Class
