'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class scorecardCharDet

    '''<summary>
    '''liBodyLoadAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liBodyLoadAction As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''idHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''numField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numField As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''valField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valField As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ddlSCHField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSCHField As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDefaultScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefaultScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKoefisien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKoefisien As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trStatus As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAttr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAttr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLimit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLimit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScore20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCount20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCount20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGood20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGood20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBad20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBad20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
