'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class scorecardRating
    
    '''<summary>
    '''liBodyLoadAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liBodyLoadAction As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''numField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numField As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblSccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSccCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSccName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSccName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''trStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trStatus As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAction As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtLimit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLimit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLimit20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtScore20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKategori20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategori20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesc20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
