'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FacilityCreditInfo
    
    '''<summary>
    '''liBodyLoadAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liBodyLoadAction As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''appno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents appno As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblAppNo_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppNo_header As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBrwName_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrwName_header As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divnotif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divnotif As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNotif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotif As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DdlJenisPengajuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlJenisPengajuan As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtBunga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBunga As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadBunga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadBunga As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''DdlFasilitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlFasilitas As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtNilaiProyek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNilaiProyek As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DdlSitemPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSitemPembayaran As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtPeruntukan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPeruntukan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DdlJenisCurr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlJenisCurr As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAvailibilityPeriode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAvailibilityPeriode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtKurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKurs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DdlSifat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSifat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtNilaiValas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNilaiValas As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNilaiRp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNilaiRp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtJangkaWaktu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJangkaWaktu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtGrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtGrace As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
End Class
